name: translator_ai
description: "A personal English learning and translation assistant for Tamil speakers."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_generative_ai: any
  flutter_tts: ^4.2.0
  speech_to_text: ^7.0.0
  shared_preferences: ^2.3.4
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
